### PR TITLE
Davis birner method

### PR DESCRIPTION
**Pull request by penmaher**
Hey Mike,

Here is the PR for the new method. It is very similar to the u250 max method but the major diffs are:
- not using one layer (250 hpa) but using uwind 400-100 hpa
- subtracting the surface wind for a cleaner stj/edj difference.
- method thresholds are 50hPa upper limit and poleward of 10 deg 

The paper is here: https://journals.ametsoc.org/doi/full/10.1175/JCLI-D-15-0336.1

The section that defines the method in the pdf is section 3a paragraph 2.

One unclear point they say is: "Linear interpolation is used to find the maximum between grid points." Not clear what this means and I did not code it in. I wanted a second opinion on this.

I will create a new comment to show you the time series of the resulting method.

### CODE REVIEW

**Comment by penmaher** [comment]
Here is the resulting time series from running the compare_two_runs.py where orange is our 2PV method (as the code was at time of submission - but it looks like it has not changed) and the blue is the davis and birner method. 

[plt_diff_timeseries_ERAI-Monthly_new-ERAI-DavisBirner.pdf](https://github.com/mkstratos/stj_pv/files/3485386/plt_diff_timeseries_ERAI-Monthly_new-ERAI-DavisBirner.pdf)

**Comment by penmaher** [comment]
I have been digging into where the biggest differences is. A nice test year is 1997 which is where the SH stj drops below -45 just after 1995. 

But this is just a false positive, see here the green line with red x. The other months are just for context when the lat was poleward of -30 for the year 1997.

test_davis_SH

So what I am saying is I think the new code I have written is fine, but just has a few differences in the resulting time series to ours. Please take a look at the code and let me know if there are any issues.

**Comment by mkstratos** [comment]
I've added a quadratic interpolation to the maximum finding (so long as the selected location is not at the boundaries), so that it doesn't snap to the grid points. @penmaher let me know if you think that works? If you agree, I'll merge it in. (After some code-style updates 😄)

**Comment by penmaher** [comment]
I have reviewed your changes. Looks good to me. Only very minor change in time series. Happy for you to include this change and any other code style changes you wish.

**Comment by mkstratos** [comment]
Great! Cleaned up some line lengths and indents, merging now.

**Comment by penmaher** [comment]
Great. Thanks for the changed and the review.

**Pull request merged**
